# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bread',
            name='grain',
            field=models.CharField(default='wheat', max_length=127),
        ),
    ]
