# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0004_remove_bread_grain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grain',
        ),
        migrations.AddField(
            model_name='bread',
            name='grain',
            field=models.CharField(default='Rye', max_length=127),
        ),
    ]
