# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homes', '0006_delete_bread'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('grain', models.CharField(default='Wheat', max_length=127)),
            ],
        ),
    ]
