# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0007_bread'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
            ],
        ),
        migrations.AlterField(
            model_name='bread',
            name='grain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.Grain'),
        ),
    ]
