# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0009_auto_20170816_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertytype',
            old_name='ptype',
            new_name='type',
        ),
    ]
